<?php

namespace App\Repository;

use App\Library\Cryptor;
use lsilva\SAK\Doctrine\AbstractRepository;
use PHPMailer\PHPMailer\PHPMailer;
use PHPMailer\PHPMailer\SMTP;
use PHPMailer\PHPMailer\Exception;
use GuzzleHttp\Client;
use Ramsey\Uuid\Uuid;

/**
 * CampanhaParticipanteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CampanhaParticipanteRepository extends AbstractRepository
{
    public function postInsert($id, $data)
    {
        $this->createAplicacao($data['campanhaId'], $id, $data);
    }

    public function deleteLogic($id)
    {
        $this->update($id, ['deletedAt' => date('Y-m-d H:i:s'), 'status' => '0']);
    }

    protected function prepareLineToImport(\StdClass $oLine)
    {
        $oReturn = new \StdClass;
        $message = null;
        $status = true;
        $em = $this->getEntityManager();

        if (property_exists($oLine, 'campanhaId')) {
            $campanha = $em->getRepository('\App\Entity\Campanha')
                ->createQueryBuilder('t')
                ->select('t.id')
                ->where('t.id = :campanhaId')
                ->setParameter('campanhaId', $oLine->campanhaId)
                ->getQuery()->getScalarResult();
        }

        if (!empty($campanha)) {
            $a = (array) $oLine;
            $oReturn->campanha_id = $this->getValueToEntity('campanhaId', $a);
            // $oReturn->participante_id = $participante[0]['id'];
            $oReturn->codigoExterno = $this->getValueToEntity('codigoExterno', $a);
            $oReturn->cpf = $this->getValueToEntity('cpf', $a);
            $oReturn->dtNascimento = $this->getValueToEntity('dtNascimento', $a);
            $oReturn->nome = $this->getValueToEntity('nome', $a);
            $oReturn->sexo = $this->getValueToEntity('sexo', $a);
            $oReturn->rua = $this->getValueToEntity('rua', $a);
            $oReturn->numero = $this->getValueToEntity('numero', $a);
            $oReturn->complemento = $this->getValueToEntity('complemento', $a);
            $oReturn->bairro = $this->getValueToEntity('bairro', $a);
            $oReturn->cidade = $this->getValueToEntity('cidade', $a);
            $oReturn->codigoLocal = $this->getValueToEntity('codigoLocal', $a);
            $oReturn->estado = $this->getValueToEntity('estado', $a);
            $oReturn->pais = $this->getValueToEntity('pais', $a);
            $oReturn->cep = $this->getValueToEntity('cep', $a);
            $oReturn->telefone = $this->getValueToEntity('telefone', $a);
            $oReturn->celular = $this->getValueToEntity('celular', $a);
            $oReturn->email = $this->getValueToEntity('email', $a);
            $oReturn->descricao = $this->getValueToEntity('descricao', $a);
        } else {
            $message = 'Campanha não encontrada';
            $status = false;
        }

        return [
            'object' => (array) $oLine, # Objeto a ser importado
            'status' => $status, # true -> Sucesso, false -> Falha
            'message' => $message, # Mensagem de erro
        ];
    }

    public function fetchCollection($params = [], $filters = [], $orders = [], $page = 1, $limit = 100)
    {
        $result = parent::fetchCollection($params, $filters, $orders, $page, $limit);
        if ($params && property_exists($params, 'download') && !empty($params->download)) {
            // Não trata
        } else {
            foreach ($result as $k => $data) {
                $result[$k]['cpf'] = Cryptor::cryptoJsAesEncrypt('123456', $result[$k]['cpf']);
                $result[$k]['nome'] = Cryptor::cryptoJsAesEncrypt('123456', $result[$k]['nome']);
            }
        }

        return $result;
    }

    protected function validParams($params)
    {
        // TODO: Obter esses campos a partir da documentação
        $requiredFields = ['campanhaId'];
        // 'codigoExterno' Deve ser validado quqnaod for participante principal
        $diff = array_diff($requiredFields, array_keys($params));
        if (!empty($diff)) {
            throw new \Exception("Os seguintes campos são obrigatórios: " . implode(', ', $diff), 1);
        }

        $objValidator = new \App\Library\ValidatorEntity;
        if (!empty($params['cpf'])) {
            $objValidator->isValidCPF('cpf', $params['cpf']);
        }
        // $objValidator->isNumber('cpf', $entity->getCpf());
        // $objValidator->isNumber('campanha_id', $entity->getCampanha()->getId());
        // $objValidator->notEmpty('nome', $entity->getInfoPessoal()->getNome());
        // $objValidator->stringMinLength('nome', $entity->getInfoPessoal()->getNome(), 4);
        // $objValidator->notEmpty('codigoExterno', $entity->getCodigoExterno());
        // $objValidator->isAlnum('codigoExterno', $entity->getCodigoExterno());
        // $objValidator->inArray('sexo', $entity->getInfoPessoal()->getSexo(), [0, 1]);
        // // $objValidator->inArray('status', $entity->getStatus(), [0, 1]);

        // if(!empty($entity->getParticipantePrincipal())) {
        //     $objValidator->notEmpty('participantePrincipalCodigo', $this->getParticipantePrincipalFromCodigo($entity->getCampanha()->getId(), null, $entity->getParticipantePrincipal()));
        // }

        // // Validação para não deixar cadastrar participante com CPF duplicado na campanha
        // $em = $this->getEntityManager();
        // $collection = $this->createQueryBuilder("t");
        // $where = "t.codigoExterno = :codigoExterno AND t.campanha = :campanhaId";
        // $where.= " AND (t.dtExclusao IS NULL OR t.dtExclusao = '0000-00-00 00:00:00')";
        // if(!is_null($entity->getId())) { // Atualização
        // 	$where .= " AND t.id <> :id";
        // 	$collection->setParameter("id", $entity->getId());
        // }
        // $collection->where($where)
        // 	->setParameter("codigoExterno", $entity->getCodigoExterno())
        // 	->setParameter("campanhaId", $entity->getCampanha()->getId());

        // if(!empty($collection->getQuery()->getScalarResult())) {
        //     $objValidator->failMessage(['Código Externo já cadastrado para outro participante nesta campanha'], 'codigoExterno');
        // }

        return true;
    }

    /**
     * Associação dos campos obtidos pelo Select e os campos que serão retornados
     * @param  boolean $toHeader
     * @return Array
     */
    protected function getAllHeadersToDisplay()
    {
        $fieldAdapter = $this->getFieldAdapter();
        return $fieldAdapter->getIds();
    }

    /**
     * Valida os campos que podem ser ordenados
     * @param  \Doctrine\ORM\QueryBuilder $collection
     * @param  Array $params
     * @return \Doctrine\ORM\QueryBuilder
     */
    protected function getOrders($collection, $params)
    {
        return $collection;
    }

    /**
     * Valida os campos que podem ser filtrados no select
     * @param  \Doctrine\ORM\QueryBuilder $collection
     * @param  Array $filters
     * @return \Doctrine\ORM\QueryBuilder
     */
    protected function getFilters($collection, $filters)
    {
        $where = '1=1';

        if (!empty($filters['somenteExcluidos']) && $filters['somenteExcluidos'] === 'yes') {
            $where .= ' AND t.deletedAt IS NOT NULL AND t.status = 0';
        } else {
            $where .= ' AND t.deletedAt IS NULL AND t.status = 1';
        }

        if (!empty($filters['id'])) {
            $where .= ' AND t.id = :id';
            $collection->setParameter('id', $filters['id']);
        }

        if (!empty($filters['campanhaId'])) {
            $where .= ' AND t.campanhaId = :campanhaId';
            $collection->setParameter('campanhaId', $filters['campanhaId']);
        }

        if (!empty($filters['empresaId'])) {
            $where .= ' AND t.empresaId = :empresaId';
            $collection->setParameter('empresaId', $filters['empresaId']);
        }

        if (!empty($filters['participantePrincipalId'])) {
            $where .= ' AND t.participantePrincipalId = :participantePrincipalId';
            $collection->setParameter('participantePrincipalId', $filters['participantePrincipalId']);
        }

        if (!empty($filters['token'])) {
            $where .= ' AND tp.token = :token';
            $collection->setParameter('token', $filters['token']);
        }

        if (!empty($filters['cpf'])) {
            $where .= ' AND t.cpf = :cpf';
            $cpf = preg_replace('/^0+/', '', $filters['cpf']);
            $collection->setParameter('cpf', $cpf);
        }

        if (!empty($filters['nome'])) {
            $where .= ' AND lower(t.nome) LIKE lower(:nome)';
            $collection->setParameter('nome', '%' . $filters['nome'] . '%');
        }

        if (!empty($filters['codigoLocal'])) {
            $where .= ' AND lower(t.codigoLocal) LIKE lower(:codigoLocal)';
            $collection->setParameter('codigoLocal', '%' . $filters['codigoLocal'] . '%');
        }

        if (!empty($filters['departamento'])) {
            $where .= ' AND lower(t.departamento) LIKE lower(:departamento)';
            $collection->setParameter('departamento', '%' . $filters['departamento'] . '%');
        }

        if (!empty($filters['matricula'])) {
            $where .= ' AND lower(t.matricula) LIKE lower(:matricula)';
            $collection->setParameter('matricula', '%' . $filters['matricula'] . '%');
        }

        if (!empty($filters['tipo'])) {
            if ($filters['tipo'] === 'principal') {
                $where .= ' AND t.participantePrincipalId IS NULL';
            } else {
                $where .= ' AND t.participantePrincipalId IS NOT NULL';
            }
        }

        if (!empty($filters['dtNascimento'])) {
            $where .= ' AND t.dtNascimento = :dtNascimento';
            $collection->setParameter('dtNascimento', $filters['dtNascimento']);
        }

        if (!empty($filters['comAdesao'])) {
            if ($filters['comAdesao'] === 'yes') {
                $where .= ' AND t.dtAceite IS NOT NULL';
            } else {
                $where .= ' AND t.dtAceite IS NULL';
            }
        }

        if (!empty($filters['createdAt'])) {
            switch ($filters['createdAt']) {
                case 'today':
                    $where .= ' AND t.createdAt BETWEEN \'' . date('Y-m-d') . ' 00:00\'';
                    $where .= ' AND \'' . date('Y-m-d') . ' 23:59:59\'';
            }
        }

        if (!empty($filters['codigoExterno'])) {
            // $where .= ' AND lower(t.codigoExterno) LIKE lower(:codigoExterno)';
            // $collection->setParameter('codigoExterno', '%' . $filters['codigoExterno'] . '%');
            // $where .= ' AND t.codigoExterno = :codigoExterno';
            $collection->leftJoin('\App\Entity\CampanhaParticipante', 'cpt', 'WITH', 'cpt.id = t.participantePrincipalId');
            $where .= ' AND  (t.codigoExterno = :codigoExterno OR cpt.codigoExterno = :codigoExterno)';
            $collection->setParameter('codigoExterno', $filters['codigoExterno']);
        }

        if (!empty($filters['codigoExternoExato'])) {
            // $where .= ' AND t.deletedAt < NOW()';
            // $where .= ' AND cast(t.codigoExterno AS CHAR(20)) like \'%:codigoExternoExato%\'';
            // $where .= ' AND CONCAT(t.codigoExterno) = :codigoExternoExato';
            // $where .= ' AND CONCAT(t.codigoExterno) like \'%:codigoExternoExato%\'';
            // $where .= ' AND CONVERT(t.codigoExterno,char) like \'%:codigoExternoExato%\'';
            $where .= ' AND t.codigoExterno = :codigoExternoExato';
            $collection->setParameter('codigoExternoExato', $filters['codigoExternoExato']);
        }

        if (!empty($filters['nomeCodigo'])) {
            $where .= ' AND (lower(t.nome) LIKE lower(:participante)';
            $where .= ' OR  t.codigoExterno = :participante_codigo)';
            $collection->setParameter('participante', '%' . $filters['nomeCodigo'] . '%');
            $collection->setParameter('participante_codigo', $filters['nomeCodigo']);
        }

        if (!empty($filters['nomeCodigoCpf'])) {
            $where .= ' AND (lower(t.nome) LIKE lower(:participante)';
            $where .= ' OR t.cpf = :participante_cpf';
            $where .= ' OR  t.codigoExterno = :participante_codigo)';
            $collection->setParameter('participante', '%' . $filters['nomeCodigoCpf'] . '%');
            $collection->setParameter('participante_codigo', $filters['nomeCodigoCpf']);
            $collection->setParameter('participante_cpf', $filters['nomeCodigoCpf']);
        }


        if (!empty($filters['codigoExternoLike'])) {
            $collection->leftJoin('\App\Entity\CampanhaParticipante', 'cpt', 'WITH', 'cpt.id = t.participantePrincipalId');
            $where .= ' AND  (t.codigoExterno LIKE :codigoExternoLike OR cpt.codigoExterno LIKE :codigoExternoLike)';
            $collection->setParameter('codigoExternoLike', '%' . $filters['codigoExternoLike'] . '%');
        }

        if (!empty($filters['matricula'])) {
            $where .= ' AND lower(t.matricula) LIKE lower(:matricula)';
            $collection->setParameter('matricula', '%' . $filters['matricula'] . '%');
        }

        $collection->where($where);
        //         $this->debbug_query_collection = true;
        return $collection;
    }

    /**
     * Query utilizada para as consultas
     * @param  Array $params
     * @return  \Doctrine\ORM\QueryBuilder
     */
    protected function getQueryToFeatchCollection()
    {
        $fieldAdapter = $this->getFieldAdapter();
        $collection = $this->createQueryBuilder("t")
            ->select($fieldAdapter->getSqlFields())
            ->leftJoin('\App\Entity\Campanha', 'cp', 'WITH', 'cp.id = t.campanhaId')
            ->leftJoin('\App\Entity\TokenParticipante', 'tp', 'WITH', 'tp.participanteId = t.id')
            ->leftJoin('\App\Entity\Empresa', 'e', 'WITH', 'e.id = t.empresaId')
            ->leftJoin('\App\Entity\CampanhaParticipantePagador', 'p', 'WITH', 'p.id = t.pagadorId');

        return $collection;
    }

    protected function setItemsToEntity($aValues, $entity = null, $oldEntity = null)
    {
        $entity = $this->getEntity();
        $em = $this->getEntityManager();

        $entity->setCodigoExterno($this->getValueToEntity('codigoExterno', $aValues, $oldEntity));
        $entity->setCampanhaId($this->getValueToEntity('campanhaId', $aValues, $oldEntity));
        $entity->setPagadorId($this->getValueToEntity('pagadorId', $aValues, $oldEntity));
        $entity->setDtAceite($this->getValueToEntity('dtAceite', $aValues, $oldEntity));
        $entity->setCodigoLocal($this->getValueToEntity('codigoLocal', $aValues, $oldEntity));
        if (is_null($oldEntity)) {
            $entity->setCreatedAt(new \DateTime());
            $entity->setUpdatedAt(new \DateTime());
            $entity->setUuid(Uuid::uuid4());
            $entity->setCol5($entity->getCodigoExterno());
        } else {
            $entity->setCreatedAt(!empty($entity->getCreatedAt()) ? $entity->getCreatedAt() : new \DateTime());
            $entity->setUpdatedAt(new \DateTime());
        }

        $entity->setDtAceiteLgpd($this->getValueToEntity('dtAceiteLgpd', $aValues, $oldEntity));
        if (empty($entity->getDtAceite())) {
            $oCampanha = $this->_em->getRepository('\App\Entity\Campanha')->findOneBy(['id' => $entity->getCampanhaId()]);
            if ($oCampanha && $oCampanha->getTipo() === 2) {
                $entity->setDtAceite(new \DateTime());
            } else {
                $entity->setDtAceite(null);
            }
        } else {
            $entity->setDtAceite(new \DateTime($entity->getDtAceite()));
        }
        $entity->setDeletedAt($this->getValueToEntity('deletedAt', $aValues, $oldEntity));
        if (empty($entity->getDeletedAt())) {
            $entity->setDeletedAt(null);
        } else {
            $entity->setDeletedAt(new \DateTime($entity->getDeletedAt()));
        }

        if (empty($entity->getDtAceiteLgpd())) {
            $entity->setDtAceiteLgpd(null);
        } elseif (!empty($entity->getDtAceiteLgpd())) {
            $entity->setDtAceiteLgpd(new \DateTime($entity->getDtAceiteLgpd()));
        }

        $entity->setEmpresaId($this->getValueToEntity('empresaId', $aValues, $oldEntity));
        $entity->setCampanhaId($this->getValueToEntity('campanhaId', $aValues, $oldEntity));
        if ($participanteId = $this->getValueToEntity('participantePrincipalId', $aValues, $oldEntity)) {
            $entity->setParticipantePrincipalId($participanteId);
        }

        $entity->setStatus($this->getValueToEntity('status', $aValues, $oldEntity));
        if (!$oldEntity && empty($entity->getStatus())) {
            $entity->setStatus(1);
        }

        if ($this->getValueToEntity('participantePrincipalCodigo', $aValues, null)) {
            $participantePrincipal = $this->getParticipantePrincipalFromCodigo($entity->getCampanhaId(), $aValues['participantePrincipalCodigo']);
            if (empty($participantePrincipal)) {
                throw new \Exception('Participante Principal nao encontrado', 404);
            } else {
                $entity->setParticipantePrincipalId($participantePrincipal['t_id']);
            }
        }

        if (!empty($entity->getParticipantePrincipalId())) {
            if (empty($participantePrincipal)) {
                $participantePrincipal = $this->getParticipantePrincipalFromCodigo($entity->getCampanhaId(), null, $entity->getParticipantePrincipalId());
            }

            if (empty($participantePrincipal)) {
                throw new \Exception('Codigo Externo nao encontrado', 404);
            }

            $codigoExterno = $this->getNextCodigoDependente($entity->getParticipantePrincipalId());
            $entity->setCodigoExterno($codigoExterno);
        }

        $entity->setCpf($this->getValueToEntity('cpf', $aValues, $oldEntity));
        $entity->setNome($this->getValueToEntity('nome', $aValues, $oldEntity));
        $entity->setMatricula($this->getValueToEntity('matricula', $aValues, $oldEntity));

        $entity->setSexo($this->getValueToEntity('sexo', $aValues, $oldEntity));
        if (empty($entity->getSexo())) {
            $entity->setSexo(0);
        }

        $entity->setDtNascimento($this->getValueToEntity('dtNascimento', $aValues, $oldEntity));
        if ($entity->getDtNascimento() === '') {
            $entity->setDtNascimento(null);
        } elseif (!empty($entity->getDtNascimento())) {
            if (strpos($entity->getDtNascimento(), '/')) {
                $entity->setDtNascimento(implode('-', array_reverse(explode('/', $entity->getDtNascimento()))));
            } elseif (is_numeric($entity->getDtNascimento())) {
                $unix_date = ($entity->getDtNascimento() - 25569) * 86400;
                $entity->setDtNascimento(gmdate("d-m-Y", $unix_date));
            }
            $entity->setDtNascimento(new \DateTime($entity->getDtNascimento()));
        }

        $entity->setTelefone($this->getValueToEntity('telefone', $aValues, $oldEntity));
        $entity->setCelular($this->getValueToEntity('celular', $aValues, $oldEntity));
        $entity->setEmail($this->getValueToEntity('email', $aValues, $oldEntity));
        $entity->setDescricao($this->getValueToEntity('descricao', $aValues, $oldEntity));

        $entity->setRua($this->getValueToEntity('rua', $aValues, $oldEntity));
        $entity->setNumero($this->getValueToEntity('numero', $aValues, $oldEntity));
        $entity->setComplemento($this->getValueToEntity('complemento', $aValues, $oldEntity));
        $entity->setBairro($this->getValueToEntity('bairro', $aValues, $oldEntity));
        $entity->setCidade($this->getValueToEntity('cidade', $aValues, $oldEntity));
        $entity->setEstado($this->getValueToEntity('estado', $aValues, $oldEntity));
        $entity->setCep($this->getValueToEntity('cep', $aValues, $oldEntity));
        $entity->setDepartamento($this->getValueToEntity('departamento', $aValues, $oldEntity));
        $entity->setCargo($this->getValueToEntity('cargo', $aValues, $oldEntity));
        // dd($entity);exit;
        return $entity;
    }

    protected function getNextCodigoDependente($participante_id)
    {
        $sql = "
            select concat(
                    codigo_externo,
                    FLOOR(RAND()*(99-1+1)+1)
                ) as codigo_externo
            from campanha_participante where id={$participante_id};
        ";

        $em = $this->getEntityManager();
        $stmt = $em->getConnection()->prepare($sql);
        $stmt->execute();
        $result = $stmt->fetchAll();

        return empty($result) ? null : $result[0]['codigo_externo'];
    }
    //     protected function setItemsToEntity($aValues, $entity = null, $oldEntity = null) {
    //         $entity = $this->getEntity();
    //         $em = $this->getEntityManager();

    //         $entity->setCodigoExterno($this->getValueToEntity('codigoExterno', $aValues, $oldEntity));
    //         $entity->setStatus($this->getValueToEntity('status', $aValues, $oldEntity));
    // 		$entity->setDtAceite($this->getValueToEntity('dtAceite', $aValues, $oldEntity));
    // 		$entity->setDtExclusao($this->getValueToEntity('dtExclusao', $aValues, $oldEntity));
    //         $entity->setCampanhaId($this->getValueToEntity('campanhaId', $aValues, $oldEntity));

    //         if ($participanteId = $this->getValueToEntity('participantePrincipalId', $aValues, $oldEntity)) {
    //             $entity->setParticipantePrincipalId($participanteId);
    //         }

    //         if (!$oldEntity && empty($entity->getStatus())) {
    //             $entity->setStatus(1);
    //         }

    //         if($this->getValueToEntity('participantePrincipalCodigo', $aValues, null)) {
    //         	$entity->participantePrincipalId = $this->getParticipantePrincipalFromCodigo($entity->getCampanhaId(), $aValues['participantePrincipalCodigo']);
    //         }

    //         $oEntidy = $em->getRepository('\App\Entity\Endereco')->updateOrCreate($oldEntity['enderecoId'], $aValues);
    // 		$oEndereco = $em->getRepository('\App\Entity\Endereco')->fetch($oEntidy['id']);

    // 		$oEntidy = $em->getRepository('\App\Entity\InfoPessoal')->updateOrCreate($oldEntity['info_pessoalId'], $aValues);
    // 		$oInfoPessoal = $em->getRepository('\App\Entity\InfoPessoal')->fetch($oEntidy['id']);
    //         $obj = $this->cast('\App\Entity\InfoPessoal',  (object) $oInfoPessoal);
    //         $entity->setInfoPessoal($obj);

    // 		$oEntidy = $em->getRepository('\App\Entity\Contato')->updateOrCreate($oldEntity['contatoId'], $aValues);
    //         $oContato = $em->getRepository('\App\Entity\Contato')->fetch($oEntidy['id']);

    //         // // $entity->setEndereco($this->cast('\App\Entity\Endereco', (object) $oEndereco));
    //         // // $entity->setContato($this->cast('\App\Entity\Contato', (object) $oContato));
    //         // // $obj = $this->cast('\App\Entity\InfoPessoal',  (object) $oInfoPessoal);
    //         // $entity->setEndereco($oEndereco);
    //         // $entity->setInfoPessoal($oInfoPessoal);
    //         // $entity->setContato($oContato);

    //         if(empty($entity->getDtAceite())) {
    //             $entity->setDtAceite(null);
    //         } else {
    //             $entity->setDtAceite(new \DateTime($entity->getDtAceite()));
    //         }

    //         if(empty($entity->getDtExclusao())) {
    //             $entity->setDtExclusao(null);
    //         } else {
    //             $entity->setDtExclusao(new \DateTime($entity->getDtExclusao()));
    //         }
    // 		// $entity->setInfoPessoal($obj);
    // // var_dump( $entity);exit;
    //         return $entity;
    //     }

    private function getParticipantePrincipalFromCodigo($campanhaId, $participanteCodigoExterno = null, $participanteId = null)
    {
        $em = $this->getEntityManager();
        $collection = $this->createQueryBuilder("t");
        $where = "t.campanhaId = :campanhaId";
        $where .= " AND t.deletedAt IS NULL";

        if (!is_null($participanteCodigoExterno)) {
            $where .= " AND t.codigoExterno = :codigoExterno";
            $collection->setParameter("codigoExterno", $participanteCodigoExterno);
        } elseif (!is_null($participanteId)) {
            $where .= " AND t.id = :id";
            $collection->setParameter("id", $participanteId);
        } else {
            return null;
        }

        $collection->where($where)->setParameter("campanhaId", $campanhaId);

        $return = $collection->getQuery()->getScalarResult();
        return empty($return) ? null : $return[0];
    }

    private function calcularIdade(\DateTime $dataNascimento): int {
        $hoje = new \DateTime(); // Data atual
        $diferenca = $hoje->diff($dataNascimento); // Calcula a diferença entre as datas
        return $diferenca->y; // Retorna a idade em anos
    }


    private function createAplicacao($campanhaId, $participanteId, $entity = [])
    {
        if (empty($campanhaId)) {
            return false;
        }

        $oCampanha = $this->_em->getRepository('\App\Entity\Campanha')
            ->findOneBy(['id' => $campanhaId]);

        if (!$oCampanha) {
            return false;
        }

        // Campanha Pré-aprovada
        if ($oCampanha->getTipo() === 2) {
            $oParams = new \Stdclass;
            $oParams->campanhasId = $campanhaId;
            $oCampanhaVacinas = $this->_em->getRepository('\App\Entity\CampanhaVacina')
                ->fetchCollection($oParams, ['campanhaId' => $campanhaId]);

            if(empty($oCampanhaVacinas)) {
                return false;
            }

            $this->_em->getRepository('\App\Entity\Aplicacao')
                ->createAplicacoes($campanhaId, $participanteId, $oCampanhaVacinas);

            // TODO: Verificar se o cache esta funcionando
            $oVacina = $this->_em->getRepository('\App\Entity\Vacina')
                ->findOneBy(['id' => $oCampanhaVacinas[0]['vacinaId']]);

            // Verifica se deve cadastrar a aplicação extra por causa do parametro da vacina
            if($oVacina && $oVacina->getParDoseExtraIdade() && $entity['dtNascimento']) {
                $idade = $this->calcularIdade(new \DateTime($entity['dtNascimento']));
                if($oVacina->getParDoseExtraIdade() >= $idade) {
                    $this->_em->getRepository('\App\Entity\Aplicacao')
                        ->createAplicacoes($campanhaId, $participanteId, $oCampanhaVacinas);
                }
            }

            $this->update($participanteId, ['dtAceite' => date('Y-m-d H:i:s')]);
        }
    }

    public function cast($destination, $sourceObject)
    {
        if (is_string($destination)) {
            $destination = new $destination();
        }
        $sourceReflection = new \ReflectionObject($sourceObject);
        $destinationReflection = new \ReflectionObject($destination);
        $sourceProperties = $sourceReflection->getProperties();
        foreach ($sourceProperties as $sourceProperty) {
            $sourceProperty->setAccessible(true);
            $name = $sourceProperty->getName();
            $value = $sourceProperty->getValue($sourceObject);
            if ($destinationReflection->hasProperty($name)) {
                $propDest = $destinationReflection->getProperty($name);
                $propDest->setAccessible(true);
                $propDest->setValue($destination, $value);
            } else {
                $destination->$name = $value;
            }
        }
        return $destination;
    }

    private function splitFiles($fileName)
    {
        $path = realpath(dirname($fileName));
        $file = urlencode(utf8_encode(basename($fileName)));
        $time = time();
        $cmd = "split -l 500 --additional-suffix=.new_ {$path}/{$file} {$path}/{$time}_";
        echo exec($cmd);

        $fileNameOk = str_replace($file, "read_{$time}", $fileName);
        $this->renameFile($fileName, $fileNameOk);

        return glob("{$path}/{$time}*");
    }

    private function getHeader($file)
    {
        $cmd = "head -n 1 {$file}";
        return exec($cmd);
    }

    private function addHeader($file, $header)
    {
        $cmd = "sed -i '1s/^/{$header}\\n/' {$file}";
        return exec($cmd);
    }

    public function renameFile($file, $newname = null)
    {
        if (empty($newname)) {
            $newname = substr($file, 0, -1);
        }
        $cmd = "mv {$file} {$newname}";
        return exec($cmd);
    }

    public function bulkInsert($file)
    {
        $time1 = time();

        $files = $this->splitFiles($file);

        $data = [
            'originalFilename' => basename($file),
            'totalSplit' => count($files)
        ];

        $em = $this->getEntityManager();
        $oProcess = $em->getRepository('\App\Entity\ProcessUploadStatus')->create($data);
        $em->flush();

        $batchSize = 20; // Define o tamanho do lote para evitar consumo excessivo de memória
        $i = 0;
        foreach ($files as $file) {
            try {
                // Se o EntityManager estiver fechado, reabre ele
                if (!$em->isOpen()) {
                    $em = $em->create(
                        $this->_em->getConnection(),
                        $this->_em->getConfiguration()
                    );
                }

                $oItem = new \App\Entity\ProcessUploadStatusItems();
                $oItem->setFilename(basename(preg_replace('/_$/', '', $file)));
                $oItem->setProcessUploadStatusId($oProcess['id']);
                $oItem->setStatus(1);
                $oItem->setCreatedAt(new \DateTime());

                $em->persist($oItem);
                // Faz o flush a cada $batchSize inserções para melhor performance
                if (($i % $batchSize) === 0) {
                    $em->flush();
                    $em->clear(); // Limpa os objetos gerenciados da memória
                }
            }
            catch (\Exception $e) {
                echo "bulkInsert: " . $e->getMessage() . "\n";
            }
            $i++;
        }
        // Dá flush no que restou no buffer
        $em->flush();
        $em->clear();

        $header = [];
        foreach ($files as $k => $file) {
            if (!$k) {
                $header = $this->getHeader($file);
            }

            if (empty($header)) {
                die("FIM - ERRO\n");
            }

            if ($k) {
                $this->addHeader($file, $header);
            }

            $this->renameFile($file);
        }

        $time2 = time();
        echo "Total de arquivos: " . count($files) . "\n";
        echo "Tempo total processamento: " . ($time2 - $time1) . "s\n";
    }

    public function getFilesToInsert($path)
    {
        $files = glob("{$path}/*.new");
        $filesLock = $this->getFilesToInsertExclude($path);

        $newFiles = [];
        foreach ($files as $file) {
            $key = str_replace('.new', '', basename($file));
            if (!in_array($key, $filesLock)) {
                $newFiles[] = $file;
            }
        }

        return $newFiles;
    }

    public function getFilesToInsertExclude($path)
    {
        $filesEx = glob("{$path}/*.lock");
        $filesLock = [];
        foreach ($filesEx as $file) {
            $filesLock[] = preg_replace('/\..*/', '',  basename($file));
        }

        return $filesLock;
    }

    public function blockFile($file)
    {
        $file = fopen("{$file}.lock", 'a');
        fclose($file);
    }

    function isEmptyRow($row) {
        foreach($row as $cell){
            if (null !== $cell) return false;
        }
        return true;
    }

    public function processFile($file)
    {
        $em = $this->getEntityManager();

        if (!file_exists($file)) {
            throw new \Exception('Arquivo nao existe!');
        }

        // Desabilitando log
        $em->getConnection()->getConfiguration()->setSQLLogger(null);
        $rustart = getrusage();

        $count = 0;
        $limit = 3500;
        $time1 = time();
        $timeInterno = time();
        $headers = [];

        $path_parts = pathinfo($file);
        $fileNameLog = $path_parts['dirname'] . '/' . $path_parts['filename'] . '.log';
        $fileLog = fopen($fileNameLog, 'a');
        if (($handle = fopen($file, "r")) !== FALSE) {
            while (($row = fgetcsv($handle, 1000, ";")) !== FALSE) {
                $count++;
                if ($count === 1) {
                    $headers = $row;
                    fputcsv($fileLog, $row, ';');
                    continue;
                }

                $data = @array_combine($headers, $row);
                $data = array_map('trim', $data);
                try {
                    if($this->isEmptyRow($data)) {
                        throw new \Exception('Linha vazia');
                    }

                    if(empty($data['campanhaId'])) {
                        throw new \Exception('Sem codigo da campanha');
                    }

                    $cloneObj = clone $this;
                    $cloneObj->create($data);
                    fputcsv($fileLog, array_merge($data, ['SUCESSO']), ';');

                    $this->_em->flush();
                    $this->_em->clear(); // Detaches all objects from Doctrine!
                } catch (\Exception $e) {
                    fputcsv($fileLog, array_merge($data, [$e->getMessage()]), ';');
                    echo ('Data Participante: ' . serialize($data) . ' | Error: ' . $e->getMessage() . "\n");
                    if (!$this->_em->isOpen()) {
                        $this->_em = $this->_em->create(
                            $this->_em->getConnection(),
                            $this->_em->getConfiguration()
                        );
                    }
                }

                if ($count % 100 === 0) {
                    $timeInternoTemp = time();
                    $time = ($timeInternoTemp - $timeInterno);
                    $timeInterno = $timeInternoTemp;
                    echo "Total pocessado [{$count}] [{$time}s]\n";
                }
                // if ($count === $limit) {
                //     echo "Limite [{$limit}] atingido \n";
                //     break;
                // }
            }
            fclose($handle);
        }
        // Limite [50] atingido
        // Memory usage: 1.24 GiB / 1.94 GiB (63.583223158977%)
        // This process used 695 ms for its computations
        // It spent 140 ms in system calls

        // Limite [500] atingido
        // Memory usage: 1.24 GiB / 1.94 GiB (63.941600398589%)
        // This process used 27722 ms for its computations
        // It spent 1107 ms in system calls
        // Overall Time spent: 241s

        $time2 = time();

        $memUsage = $this->getServerMemoryUsage(false);
        echo sprintf(
            "Memory usage: %s / %s (%s%%)",
            $this->getNiceFileSize($memUsage["total"] - $memUsage["free"]),
            $this->getNiceFileSize($memUsage["total"]),
            $this->getServerMemoryUsage(true)
        );

        echo "\n";
        $ru = getrusage();
        echo "This process used " . $this->rutime($ru, $rustart, "utime") .
            " ms for its computations\n";
        echo "It spent " . $this->rutime($ru, $rustart, "stime") .
            " ms in system calls\n";
        echo "Overall Time spent: " . ($time2 - $time1) . "s\n";
    }

    /**
     * @deprecated
     */
    public function bulkInsertOld($file)
    {
        $em = $this->getEntityManager();
        // Desabilitando log
        $em->getConnection()->getConfiguration()->setSQLLogger(null);
        $rustart = getrusage();

        $count = 0;
        $headers = [];
        $batchSize = 100;
        $limit = 3500;
        $time1 = time();
        $timeInterno = time();
        if (($handle = fopen($file, "r")) !== FALSE) {
            while (($row = fgetcsv($handle, 1000, ";")) !== FALSE) {
                $count++;
                if ($count === 1) {
                    $headers = $row;
                    continue;
                }

                // Sem lote / Processado: 100
                // Memory usage: 1.86 GiB / 1.94 GiB (95.874836700026%)
                // This process used 531 ms for its computations
                // It spent 235 ms in system calls

                // Lote: 20 / Processado: 100
                // Memory usage: 1.86 GiB / 1.94 GiB (95.899552371724%)
                // This process used 546 ms for its computations
                // It spent 242 ms in system calls

                // Lote: 100 / Processado: 3500
                // Memory usage: 1.87 GiB / 1.94 GiB (96.047846401908%)
                // This process used 36964 ms for its computations
                // It spent 7918 ms in system calls

                // Sem lote / Processado: 3500
                // Memory usage: 1.84 GiB / 1.94 GiB (94.676126622702%)
                // This process used 18712 ms for its computations
                // It spent 9110 ms in system calls

                // Lote: 50 / Processado: 500
                // Memory usage: 1.24 GiB / 1.94 GiB (63.719551665562%)
                // This process used 5906 ms for its computations
                // It spent 1276 ms in system calls
                // Overall Time spent: 1300s


                $data = array_combine($headers, $row);
                $data['campanhaId'] = 1;
                $cloneObj = clone $this;
                $entity = $cloneObj->setItemsToEntity($data, $cloneObj->getEntity());
                // var_dump($entity);
                $em->persist($entity);
                // $em->flush();
                // $em->clear(); // Detaches all objects from Doctrine!

                if (($count % $batchSize) === 0) {
                    echo "FLUSH LOTE {$count}\n";
                    $em->flush();
                    $em->clear(); // Detaches all objects from Doctrine!
                }

                if ($count % ($limit / 5) === 0) {
                    $timeInternoTemp = time();
                    $time = ($timeInternoTemp - $timeInterno);
                    $timeInterno = $timeInternoTemp;
                    echo "Total pocessado [{$count}] [{$time}s]\n";
                }

                if ($count === $limit) {
                    echo "Limite [{$limit}] atingido \n";
                    break;
                }
            }
            fclose($handle);

            $em->flush();
            $em->clear(); // Detaches all objects from Doctrine!
        }

        $time2 = time();

        $memUsage = $this->getServerMemoryUsage(false);
        echo sprintf(
            "Memory usage: %s / %s (%s%%)",
            $this->getNiceFileSize($memUsage["total"] - $memUsage["free"]),
            $this->getNiceFileSize($memUsage["total"]),
            $this->getServerMemoryUsage(true)
        );

        echo "\n";
        $ru = getrusage();
        echo "This process used " . $this->rutime($ru, $rustart, "utime") .
            " ms for its computations\n";
        echo "It spent " . $this->rutime($ru, $rustart, "stime") .
            " ms in system calls\n";
        echo "Overall Time spent: " . ($time2 - $time1) . "s\n";
        // $batchSize = 20;
        // for ($i = 1; $i <= 10000; ++$i) {
        //     $entity = $this->setItemsToEntity($data, $this->getEntity());
        //     $user->setStatus('user');
        //     $user->setUsername('user' . $i);
        //     $user->setName('Mr.Smith-' . $i);
        //     $em->persist($user);
        //     if (($i % $batchSize) === 0) {
        //         $em->flush();
        //         $em->clear(); // Detaches all objects from Doctrine!
        //     }
        // }
        // $em->flush(); //Persist objects that did not make up an entire batch
        // $em->clear();
    }

    function rutime($ru, $rus, $index)
    {
        return ($ru["ru_$index.tv_sec"] * 1000 + intval($ru["ru_$index.tv_usec"] / 1000))
            -  ($rus["ru_$index.tv_sec"] * 1000 + intval($rus["ru_$index.tv_usec"] / 1000));
    }

    function getServerMemoryUsage($getPercentage = true)
    {
        $memoryTotal = null;
        $memoryFree = null;

        if (stristr(PHP_OS, "win")) {
            // Get total physical memory (this is in bytes)
            $cmd = "wmic ComputerSystem get TotalPhysicalMemory";
            @exec($cmd, $outputTotalPhysicalMemory);

            // Get free physical memory (this is in kibibytes!)
            $cmd = "wmic OS get FreePhysicalMemory";
            @exec($cmd, $outputFreePhysicalMemory);

            if ($outputTotalPhysicalMemory && $outputFreePhysicalMemory) {
                // Find total value
                foreach ($outputTotalPhysicalMemory as $line) {
                    if ($line && preg_match("/^[0-9]+\$/", $line)) {
                        $memoryTotal = $line;
                        break;
                    }
                }

                // Find free value
                foreach ($outputFreePhysicalMemory as $line) {
                    if ($line && preg_match("/^[0-9]+\$/", $line)) {
                        $memoryFree = $line;
                        $memoryFree *= 1024;  // convert from kibibytes to bytes
                        break;
                    }
                }
            }
        } else {
            if (is_readable("/proc/meminfo")) {
                $stats = @file_get_contents("/proc/meminfo");

                if ($stats !== false) {
                    // Separate lines
                    $stats = str_replace(array("\r\n", "\n\r", "\r"), "\n", $stats);
                    $stats = explode("\n", $stats);

                    // Separate values and find correct lines for total and free mem
                    foreach ($stats as $statLine) {
                        $statLineData = explode(":", trim($statLine));

                        //
                        // Extract size (TODO: It seems that (at least) the two values for total and free memory have the unit "kB" always. Is this correct?
                        //

                        // Total memory
                        if (count($statLineData) == 2 && trim($statLineData[0]) == "MemTotal") {
                            $memoryTotal = trim($statLineData[1]);
                            $memoryTotal = explode(" ", $memoryTotal);
                            $memoryTotal = $memoryTotal[0];
                            $memoryTotal *= 1024;  // convert from kibibytes to bytes
                        }

                        // Free memory
                        if (count($statLineData) == 2 && trim($statLineData[0]) == "MemFree") {
                            $memoryFree = trim($statLineData[1]);
                            $memoryFree = explode(" ", $memoryFree);
                            $memoryFree = $memoryFree[0];
                            $memoryFree *= 1024;  // convert from kibibytes to bytes
                        }
                    }
                }
            }
        }

        if (is_null($memoryTotal) || is_null($memoryFree)) {
            return null;
        } else {
            if ($getPercentage) {
                return (100 - ($memoryFree * 100 / $memoryTotal));
            } else {
                return array(
                    "total" => $memoryTotal,
                    "free" => $memoryFree,
                );
            }
        }
    }

    function getNiceFileSize($bytes, $binaryPrefix = true)
    {
        if ($binaryPrefix) {
            $unit = array('B', 'KiB', 'MiB', 'GiB', 'TiB', 'PiB');
            if ($bytes == 0) return '0 ' . $unit[0];
            return @round($bytes / pow(1024, ($i = floor(log($bytes, 1024)))), 2) . ' ' . (isset($unit[$i]) ? $unit[$i] : 'B');
        } else {
            $unit = array('B', 'KB', 'MB', 'GB', 'TB', 'PB');
            if ($bytes == 0) return '0 ' . $unit[0];
            return @round($bytes / pow(1000, ($i = floor(log($bytes, 1000)))), 2) . ' ' . (isset($unit[$i]) ? $unit[$i] : 'B');
        }
    }

    function getMensagemAdesaoCancelar($oCampanha)
    {
        $linkAdesao = 'sgcsaude.com.br/adesao/' . $oCampanha->getLinkAdesao();

        $mensagemHTML = '
        <meta charset="utf-8"/>
            <figure style="text-align: center;">
                <img src="https://vacinar.com.br//img/2020/icone-logoVacinarColor.gif" />
            </figure>
            <div class="" style="width:100%;font-family:Arial;line-height:22px;border:2px solid #ffffff; margin:0 auto; padding:20px; background-color:#F2F2F2;font-size:14px;">
                <div class="" style="padding:10px; width:70%;font-family:Arial;line-height:22px;border:2px solid #efefef; margin:0 auto; padding:20px; background-color:#ffffff;font-size:14px;">
                    <p style="text-align: center;"><b style="font-size:18px;"> ' .  utf8_encode($oCampanha->getNome()) . ' CANCELAMENTO DE ADESÃO</b></p>
                    <p><b>A adesão foi cancelada com sucesso! </b></p>
                    <p>Para consulta e impressão do comprovante de adesão acesse <a href="http://' . $linkAdesao . '" target="_blank">' . $linkAdesao . '</a></p>
                    <p>Para melhor navegabilidade copie e cole o link na barra de endereço do Google Chrome</p>
                    <p>Cancelamentos somente até ' . $oCampanha->getDtAdesaoFim()->format('d/m/Y') . '. Após essa data, não será possível editar e cancelar a reserva de dose solicitada.</p>
                    <br>
                    <p>Atenciosamente,<br>SGC Saúde</p>
                </div>
            </div>
        ';

        return $mensagemHTML;
    }

    function getMensagemAdesao($oCampanha)
    {
        $linkAdesao = 'sgcsaude.com.br/adesao/' . $oCampanha->getLinkAdesao();

        $mensagemHTML = '
        <meta charset="utf-8"/>
            <figure style="text-align: center;">
                <img src="https://vacinar.com.br//img/2020/icone-logoVacinarColor.gif" />
            </figure>
            <div class="" style="width:100%;font-family:Arial;line-height:22px;border:2px solid #efefef; margin:0 auto; padding:20px; background-color:#ffffff;font-size:14px;">
                <div class="" style="padding:10px; width:70%;font-family:Arial;line-height:22px;border:2px solid #efefef; margin:0 auto; padding:20px; background-color:#ffffff;font-size:14px;">
                    <p style="text-align: center;"><b style="font-size:18px;"> ' . utf8_encode($oCampanha->getNome()) . ' - ACEITE DO TERMO</b></p>
                    <p><b>A adesão foi realizada com sucesso! </b></p>
                    <p>Para consulta e impressão do comprovante de adesão acesse <a href="http://' . $linkAdesao . '" target="_blank">' . $linkAdesao . '</a></p>
                    <p>Para melhor navegabilidade copie e cole o link na barra de endereço do Google Chrome</p>
                    <p>Cancelamentos somente até <b>' . $oCampanha->getDtAdesaoFim()->format('d/m/Y') . '</b>. Após essa data, não será possível editar e cancelar a reserva de dose solicitada.</p>
                    <br>
                    <p>Atenciosamente,<br>SGC Saúde</p>
                </div>
            </div>
        ';

        $mensagemHTMLTokio = '
        <meta charset="utf-8"/>
            <figure style="text-align: center;">
                <img src="https://vacinar.com.br//img/2020/icone-logoVacinarColor.gif" />
            </figure>
            <div class="" style="width:100%;font-family:Arial;line-height:22px;border:2px solid #efefef; margin:0 auto; padding:20px; background-color:#ffffff;font-size:14px;">
                <div class="" style="padding:10px; width:70%;font-family:Arial;line-height:22px;border:2px solid #efefef; margin:0 auto; padding:20px; background-color:#ffffff;font-size:14px;">
                    <p style="text-align: center;"><b style="font-size:18px;"> ' . utf8_encode($oCampanha->getNome()) . ' - ACEITE DO TERMO</b></p>
                    <p><b>Sua inscrição foi realizada com sucesso!</b></p>
                    <p>O RH fará a validação dos dados até o dia <b>27/09/2023</b> e caso você não receba um e-mail de cancelamento considere sua inscrição aprovada.</p>
                    <p><b>Atenção:</b> Recomendamos que confirme no comprovante de adesão no campo informações dos participantes que consta o seu nome e o nome dos seus dependentes, se for o caso.</p>
                    <p>Para consulta e impressão do comprovante de adesão acesse <a href="http://' . $linkAdesao . '" target="_blank">' . $linkAdesao . '</a>.</p>
                    <p>Para melhor navegabilidade copie e cole o link na barra de endereço do Google Chrome.</p>
                    <p>Cancelamentos somente até <b>22/09/2023</b>. Após essa data, não será possível editar e cancelar a reserva de dose solicitada.</p>
                    <br>
                    <p>Atenciosamente,<br>SGC Saúde</p>
                </div>
            </div>
        ';

        if ($oCampanha->getId() == 202) {
            return $mensagemHTML = $mensagemHTMLTokio;
        }

        return $mensagemHTML;
    }

    function sendEmail($campanhaId, $to, $tipo)
    {
        $oCampanha = $this->_em->getRepository('\App\Entity\Campanha')
            ->findOneBy(['id' => $campanhaId]);

        switch ($tipo) {
            case 'adesao':
                $subject = 'Vacinar - Aceite de Termo';
                $mensagemHTML = $this->getMensagemAdesao($oCampanha);
                break;
            case 'cancelar_adesao':
                $subject = 'Vacinar - Cancelamento de Adesão';
                $mensagemHTML = $this->getMensagemAdesaoCancelar($oCampanha);
                break;
            default:
                throw new \Exception('Bad Request!', 400);
        }

        $params = [
            'to' => $to,
            'subject' => $subject,
            'content' => $mensagemHTML
        ];

        $url = 'https://sgcsaude.com.br/sce/enviar_email.php';
        $client = new Client([
            'verify' => false,
            // Base URI is used with relative requests
            'base_uri' => $url,
            // You can set any number of default request options.
            // 'timeout'  => 2.0,
        ]);

        $response = $client->request('POST', $url, [
            'form_params' => $params
        ]);
        echo $response->getBody()->read(4);

        return 'enviado';
    }

    public function getTotalAdesaoParticipante($filters)
    {
        $collection = $this->createQueryBuilder("t")
            ->select("
                CASE WHEN t.dtAceite IS NULL THEN 'semAceite' ELSE 'comAceite' END AS totalAceite,
                COUNT(t.id) AS total
            ")
            ->leftJoin('\App\Entity\Empresa', 'emp', 'WITH', 'emp.id = t.empresaId')
            ;

        $where = '1=1 ';
        $where .= ' AND t.deletedAt IS NULL';
        $where .= ' AND t.campanhaId = :campanhaId';
        $collection->setParameter('campanhaId', $filters['campanhaId']);

        if (!empty($filters['empresaId'])) {
            $where .= ' AND t.empresaId = :empresaId ';
            $collection->setParameter('empresaId', $filters['empresaId']);
        }

        if (!empty($filters['uf'])) {
            $where .= ' AND emp.estado = :uf ';
            $collection->setParameter('uf', $filters['uf']);
        }

        $collection->where($where);

        $group = ' totalAceite ';
        $result = $collection->groupBy($group)->getQuery()->getResult();

        return $result;
    }
}
